services:
  fastapi:
    build: ./fastapi/
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/app:/app

  nuxt:
    build: ./nuxt/
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
