services:
  fastapi:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/app:/app

  nuxt:
    build: ./nuxt/
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
    depends_on:
      - fastapi
